[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
termion = "2.0.1"
console = "0.15.5"
clearscreen = "2.0.1"
tokio = "1.28.0"
device_query = "1.1.3"